### ISSUE TITLE
About "SDK for Zedboard" is operating on which OS, Windows or Ubuntu?

### ISSUE THREAD

**Issue by TSeminent** [dhm2013724/yolov2_xilinx_fpga#118]
I wonder the SDK repo is operating on which OS.I installed Vitis IDE2019.2 to finish SDK repo in this project,but something goes wrong eventually,as below shows:
![image](https://user-images.githubusercontent.com/85739983/225243300-2ef5eada-9d91-4766-a4b5-36074e97ce09.png)
How can I solve this error?Should I use VitisIDE2019.2 in Ubuntu instead of Windows?

**Comment by jieun0904** [comment]
Did you resolve it?
