### ISSUE TITLE
vivado 2018.3 hls problem

### ISSUE THREAD

**Issue by Diezel66** [dhm2013724/yolov2_xilinx_fpga#19]
when I run hls, there was a problem:

ERROR: [HLS 200-70] Compilation errors found: In file included from cnn.cpp:1:
cnn.cpp:172:59: error: conditional expression is ambiguous; 'typename ap_int_base<6, false>::RType<3, false>::plus' (aka 'ap_uint<7>') can be converted to 'int' and vice versa
 ap_uint<6> T2R_bound = ((t2_local + T2R)<(((26 -1)*2 +3))?(t2_local + T2R):(((26 -1)*2 +3)));

how can I solve it?Thank you very much!

**Comment by Diezel66** [comment]
> when I run hls, there was a problem:
> 
> ERROR: [HLS 200-70] Compilation errors found: In file included from cnn.cpp:1:
> cnn.cpp:172:59: error: conditional expression is ambiguous; 'typename ap_int_base<6, false>::RType<3, false>::plus' (aka 'ap_uint<7>') can be converted to 'int' and vice versa
> ap_uint<6> T2R_bound = ((t2_local + T2R)<(((26 -1)*2 +3))?(t2_local + T2R):(((26 -1)*2 +3)));
> 
> how can I solve it?Thank you very much!

**Comment by Accioy** [comment]
I met the same problem. Have you solved it?

**Comment by Diezel66** [comment]
it very simple,150MHz clock brank  seems to have bug. you should choose another branch and run it
