### ISSUE TITLE
where is the 'yolov2_w_reorg_bn_ap16_short16.bin'

### ISSUE THREAD

**Issue by lyn2333** [dhm2013724/yolov2_xilinx_fpga#2]
Hi,
When I run the yolov2.ipynq , I can not find the yolov2_w_reorg_bn_ap16_short16.bin and yolov2_b_ap16_short16.bin. Please help me.

**Comment by lyn2333** [comment]
oo，I find it, I am really silly,you are really good

**Comment by MonalPatel** [comment]
where did you find this files?
