### ISSUE TITLE
ZYNQ7 Processing System模块缺少管脚

### ISSUE THREAD

**Issue by njuhang** [dhm2013724/yolov2_xilinx_fpga#22]
你好。在vivado目录的第二步里面，Block Design添加上述ip的时候，管脚和图中所示无法对应，其他的都可以手动添加，但是IRQ_F2P这个脚是灰色的无法添加。于是考虑使用文档所述的pynq_revC.tcl和PYNQ-Z1_C.xdc文件进行设置和约束，但是不知道如何使用这两个文件呢？使用source pynq_revC.tcl命令好像没有产生任何效果。

**Comment by wei8171023** [comment]
请问你这个BLOCK design连接问题解决了吗

**Comment by evanlee2021** [comment]
您好，我遇到了同样的问题，请问您这个问题解决了吗？

**Comment by TSeminent** [comment]
您好，我也出现了管脚和图片无法对应的情况，请问您解决了吗

**Comment by MWHYNOT** [comment]
@njuhang ，大佬请问后来怎么解决的

**Comment by njuhang** [comment]
抱歉各位，过去太久了，已经完全忘记当时的情况了。
