### ISSUE TITLE
使用vivado SDK按照作者的petalinux生成的镜像，无法读取yolov2.cfg文件

### ISSUE THREAD

**Issue by ning11111** [dhm2013724/yolov2_xilinx_fpga#32]
使用vivado SDK按照作者的petalinux生成的镜像，无法读取yolov2.cfg文件，希望大佬给与解答，感激不尽，
![image](https://user-images.githubusercontent.com/54941335/64339272-3810e500-d016-11e9-8115-aa4f2a2e661c.png)

**Comment by dhm2013724** [comment]
兄弟，你visual studio版报错吗？那个不报错，这个应该也不会啊。。。

**Comment by ning11111** [comment]
HLS仿真的跑过了 然后用官方给的pynq2.3版本镜像跑pynq代码也跑通了，当我尝试去使用SDK的时候，用petalinux自己生成镜像就无法读取yolo.cfg文件，用官方的镜像事可以读取yolo.cfg文件的，希望大佬给解答一下，感激不尽




------------------ 原始邮件 ------------------
发件人: "dhm2013724"<notifications@github.com>; 
发送时间: 2019年9月5日(星期四) 晚上7:51
收件人: "dhm2013724/yolov2_xilinx_fpga"<yolov2_xilinx_fpga@noreply.github.com>; 
抄送: "牧"<1976205061@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [dhm2013724/yolov2_xilinx_fpga] 使用vivado SDK按照作者的petalinux生成的镜像，无法读取yolov2.cfg文件 (#32)




兄弟，你visual studio版报错吗？那个不报错，这个应该也不会啊。。。

**Comment by ning11111** [comment]
HLS仿真的跑过了 然后用官方给的pynq2.3版本镜像跑pynq代码也跑通了，当我尝试去使用SDK的时候，用petalinux自己生成镜像就无法读取yolo.cfg文件，用官方的镜像是可以读取yolo.cfg文件的，希望大佬给解答一下，感激不尽

**Comment by ning11111** [comment]
vs没有报错 软件代码没有问题，可能镜像的问题，我用的是vivado 2019.1

**Comment by dhm2013724** [comment]
你确定一下SDK里面用了静态链接没有？yolov2.cfg一般没问题

**Comment by ning11111** [comment]
![image](https://user-images.githubusercontent.com/54941335/64339981-b6ba5200-d017-11e9-933f-9d2e63700ac0.png)
是这个吗？用了

**Comment by dhm2013724** [comment]
![image](https://user-images.githubusercontent.com/15927157/64340173-1d3f7000-d018-11e9-845e-50bfdea4178f.png)
你这说明sections->front是Null啊，你确定一下yolov2.cfg存不存在，然后去看一下read_cfg函数；这边可以把filename输出来看一下
![image](https://user-images.githubusercontent.com/15927157/64340423-b4a4c300-d018-11e9-8dcd-f0baf52b9384.png)
确定一下，make_list函数有没有跑过；会gdb的话，GDB；不会的话，加printf看看

**Comment by ning11111** [comment]
![image](https://user-images.githubusercontent.com/54941335/64340343-832bf780-d018-11e9-8dc5-1ad4b73f1d24.png)
cfg在同一级目录下，确实是有的，而且我用官方pynq2.3去执行的时候，这一步是可以通过的，同时如果没有cfg文件，这里是要报错找不到的
![image](https://user-images.githubusercontent.com/54941335/64340550-05b4b700-d019-11e9-901e-32eaf00ec640.png)

**Comment by ning11111** [comment]
![image](https://user-images.githubusercontent.com/54941335/64341051-25001400-d01a-11e9-8484-9e02d5958698.png)
![image](https://user-images.githubusercontent.com/54941335/64341084-36e1b700-d01a-11e9-855f-d0d12d06b3de.png)
可以发现print的n的值是1621784，并不为零，所以下一步无法通过

**Comment by ning11111** [comment]
![image](https://user-images.githubusercontent.com/54941335/64341225-7a3c2580-d01a-11e9-9ed9-d9d91b3ce54c.png)
![image](https://user-images.githubusercontent.com/54941335/64341238-81633380-d01a-11e9-9036-20a003c5d00d.png)
可以发现print的n的值是1621784，并不为0，所以后面无法通过

**Comment by ning11111** [comment]
但是后面无法通过

**Comment by dhm2013724** [comment]
> 但是后面无法通过

你可以试试，用同样的cfg在vs里试试，然后比对一下read_cfg里的各部分的输出

**Comment by ning11111** [comment]
![image](https://user-images.githubusercontent.com/54941335/64341712-8379c200-d01b-11e9-9434-9f0aab7088b4.png)
![image](https://user-images.githubusercontent.com/54941335/64341783-adcb7f80-d01b-11e9-928a-5ea7a5d270da.png)
![image](https://user-images.githubusercontent.com/54941335/64341729-8c6a9380-d01b-11e9-8e17-146ad2bb45fb.png)
对不起，我刚才表述有误，应该是可以看到第一个打印数值file是1621784，后面第二个打印数值n值为0，说明文件读入但是输出是0，应该是中间这一小段代码出现了问题

**Comment by ning11111** [comment]
感谢您的指点，发生了一个很奇怪的现象就是这个cfg文件点进去看起来和正常的一样，但是文件大小却是0，可能实我在复制的过程中出现了问题，我有重新替换一个以后，代码即可运行，感谢指点，
