### ISSUE TITLE
PYNQ - predicting only for one class

### ISSUE THREAD

**Issue by chesterkyles** [dhm2013724/yolov2_xilinx_fpga#39]
I have a modified version of the yolov2.cfg and yolov2.weights to predict only for one class. I know for sure that I need to modify some codes especially here: 

![image](https://user-images.githubusercontent.com/39494439/68179213-efe85180-ffc9-11e9-8eb8-d487e0e5848a.png)

Can you tell me what these variables are? and also how to modify in accordance to the cfg file? Can this be also applied if i want to change it to yolov2-tiny? 

Thank you. Hoping for your feedback.

**Comment by dhm2013724** [comment]
> I have a modified version of the yolov2.cfg and yolov2.weights to predict only for one class. I know for sure that I need to modify some codes especially here:
> ![USER_SCOPED_TEMP_DATA_orca-image-1410195675](https://user-images.githubusercontent.com/39494439/68106562-f240a200-ff1c-11e9-837d-c4a7a34e9ebe.jpeg)
> 
> Can you tell me what these variables are? and also how to modify in accordance to the cfg file? Can this be also applied if i want to change it to yolov2-tiny?
> 
> Thank you. Hoping for your feedback.

You should first read some papers about quantization(references [3] and [6]), and read the software version about weight quantization.

**Comment by chesterkyles** [comment]
Thank you.
I already discovered what are the variables except for inputQ, weightQ, and biasQ. If this is related to quantization then i'll be reading some papers.

**Comment by chesterkyles** [comment]
Can you at least described what are these variables (inputQ, weightQ, betaQ)?

**Comment by dhm2013724** [comment]
WeightQ and BetaQ are quantized params about Weight quantizations, and InputQ is about input/output feature maps quantizations. The ieda for these two quantizaiton is simliar, just to use fixed point operaitons replace float point ops. So, it needs to decide the fraction bits for every fixed point data, and it is also related to the quantization error measure after data quantization.

**Comment by chesterkyles** [comment]
Thank you. Follow up question, do I still need to modify the YOLO_FPGA IP block (cnn.cpp) if i need to change it to tiny-yolov2? or just the network data? Thank you.
