### ISSUE TITLE
LUT overflow

### ISSUE THREAD

**Issue by xiaoguoer** [dhm2013724/yolov2_xilinx_fpga#40]
Hi, I tried to run c synthesis with your code in /hls/src. And I set YOLO2_FPGA as top function.
But the result implies that LUT has overflow. And clock cannot reach the requirement either.
![yolo](https://user-images.githubusercontent.com/21198126/68296277-35db0d80-00cf-11ea-86c5-30cf3dc83caa.png)
what's going wrong?

**Comment by chesterkyles** [comment]
The author mentioned it in the Readme stating:

> Oh, this part is too complicated to brightly intoduce. Current design didnt implemment C/RTL simulation, because that testbench always overflow! if anyone can solve it, please tell me and upload it, Thanks!

**Comment by dhm2013724** [comment]
> Hi, I tried to run c synthesis with your code in /hls/src. And I set YOLO2_FPGA as top function.
> But the result implies that LUT has overflow. And clock cannot reach the requirement either.
> ![yolo](https://user-images.githubusercontent.com/21198126/68296277-35db0d80-00cf-11ea-86c5-30cf3dc83caa.png)
> what's going wrong?

The hls C synthesis's resource consumption is not accurate, especially in LUT and FF. If you want to evaluate the accurate resource consumption, you can click vivado synthsis, place and route, when you want to package this ip.
