### ISSUE TITLE
Generate bitstream error

### ISSUE THREAD

**Issue by chesterkyles** [dhm2013724/yolov2_xilinx_fpga#41]
Hi, i am trying to replicate your vivado block diagram. I just followed what is on the tcl file. However, i have timing issues during implementation.

![image](https://user-images.githubusercontent.com/39494439/68574806-ad30e880-04a5-11ea-93fd-01d9f6535692.png)

Have you encountered these warnings? I tried to ignore them but bitstream seems not fine when i tried to use it for the overlay. Have you added any timing constraints? 

Thank you. Hoping for your feedback.

**Comment by dhm2013724** [comment]
> Hi, i am trying to replicate your vivado block diagram. I just followed what is on the tcl file. However, i have timing issues during implementation.
> 
> ![image](https://user-images.githubusercontent.com/39494439/68574806-ad30e880-04a5-11ea-93fd-01d9f6535692.png)
> 
> Have you encountered these warnings? I tried to ignore them but bitstream seems not fine when i tried to use it for the overlay. Have you added any timing constraints?
> 
> Thank you. Hoping for your feedback.

I have just returned from a business trip. Yes, the timing warning can be ignored, just test it in real chip.

**Comment by chesterkyles** [comment]
Okay. Thank you. I had replicated your code. I also added Video IP block and GPIO IP for the buttons, switches, and LEDs. It is running at 0.35 fps. I'm currently trying to modify it for Tiny-Yolov2 in order to achieve higher fps.
