### ISSUE TITLE
你好，我想问一下关于地址分配的细节

### ISSUE THREAD

**Issue by xbdxwyh** [dhm2013724/yolov2_xilinx_fpga#42]
我在zynq7020上面复现您的代码，我想先问一下导出IP核以后不进行c仿真可以吗？
然后，我在blockdesign中遇到了**[BD 41-971]**显示地址分配错误的问题还有**[BD 41-703]**的问题，所以我想问一下您遇到过这种问题吗
![Screenshot from 2019-11-13 07-17-18](https://user-images.githubusercontent.com/28527272/68859771-fcd01800-0722-11ea-881f-a4f1bd400ff8.png)
我不知道应该如何分配地址，如果您了解的话麻烦分享一下如何解决这种问题的细节
谢谢

**Comment by dhm2013724** [comment]
这是因为你没有在address editor里面合理的分配各接口的地址。一般情况下，Vivado会自动帮你分配，出现这种情况的话，请把里面的所有地址全部unmap，再让vivado map到缺省地址范围

**Comment by xbdxwyh** [comment]
好的，已经解决了，多谢您的及时解答

**Comment by xbdxwyh** [comment]
您好，我在SD卡上分区pax以后，结果出现Unable to mount root fs的错误，请问您遇到过这种错误吗
