### ISSUE TITLE
Can you help with Tiny Yolov2 Software Simulation?

### ISSUE THREAD

**Issue by chesterkyles** [dhm2013724/yolov2_xilinx_fpga#44]
Hi, I have modified the software simulation codes for yolov2 especially the weight_offset and beta_offset. I wanted to get the ap16 bin files for weights and beta. This is the modification:

```
void yolov2_hls_ps(network *net, float *input)
{
	int x;

	network orig = *net;
	net->input = input;

	int weight_offset[16] = {432, 4608, 18432, 73728, 294912, 1179648, 4718592, 4718592, 1958400, 0, 0, 0, 0, 0, 0, 0};
	int beta_offset[16] = {16, 32, 64, 128, 256, 512, 1024, 512, 425, 0, 0, 0, 0, 0, 0, 0};
	int offset_index = 0;

	float *Weight_buf = (float *)calloc(51869376/4,sizeof(float));
	float *Beta_buf   = (float *)calloc(11876/4,sizeof(float));

        MEM_LEN (416*416*16+208*208*32)
	float *Memory_buf = (float*)calloc(MEM_LEN+1024+1024,sizeof(float));
	float *Memory_top = Memory_buf+1024;
	float *Memory_bottom = Memory_top + MEM_LEN;
	memcpy(Memory_top,input,416*416*3*sizeof(float));//416x416x3 input_pic

	float* in_ptr[16];
	float* out_ptr[16];

	for(x=0;x<15;x++)
	{
		if(x%2==0)
		{
			in_ptr[x] = Memory_top;
			out_ptr[x] = Memory_bottom - net->layers[x].outputs ;
		}
		else
		{
			in_ptr[x] = out_ptr[x-1];
			out_ptr[x] = Memory_top;
		}
	}

	in_ptr[15] = out_ptr[14];

```

However, it cannot predict. Do i still need to modify the "_YOLO2_FPGA_" function? What are the necessary modifications for the tiny yolov2? Thank you. Hoping for your reply.

**Comment by chesterkyles** [comment]
Hi @dhm2013724  @clancylea , i have successfully modify it for tiny_yolov2. 
![Capture](https://user-images.githubusercontent.com/39494439/69029967-3cdc1700-0a11-11ea-9c0f-9644b0789d0d.PNG)

However, when running to PYNQ using the generated bin files and the values for quantization, output png has messy labels/bounding boxes.

**Comment by chesterkyles** [comment]
![image](https://user-images.githubusercontent.com/39494439/69319294-dd347480-0c79-11ea-9a32-474dbb0affb4.png)
I successfully simulated for tiny-yolov2 . However, i got problem in integrating it with PYNQ. There's probably wrong with my network data passed to the YOLO2_FPGA function.
![image](https://user-images.githubusercontent.com/39494439/69319379-06550500-0c7a-11ea-98ac-8f108465a479.png)

**Comment by chesterkyles** [comment]
I have found the issue. Issue is in the pooling layer.
```
output_w = (layerw[i] - layersize[i])//layerstride[i] + 1 
output_h = (layerh[i] - layersize[i])//layerstride[i] + 1  
```

**Comment by zzulb** [comment]
Hi，@chesterkyles. Can you send the revised project file? The weight file size I used is 44906176. And the result is wrong. Thanks!

**Comment by vvv241** [comment]
> output_w = (layerw[i] - layersize[i])//layerstride[i] + 1 
> output_h = (layerh[i] - layersize[i])//layerstride[i] + 1

Hi,I meet the same problem.What's wrong with the codes??
