### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by Patosga** [dhm2013724/yolov2_xilinx_fpga#51]
Hi,

When I try to run the application, it fails with:

`Couldn't open file: weightsv2_comb_reorg_ap16.bin`

I think the same will happen when I try to load `biasv2_comb_ap16.bin` and perhaps some other files. Is there any way I can get the missing files?

**Comment by dhm2013724** [comment]
> Hi,
> 
> When I try to run the application, it fails with:
> 
> `Couldn't open file: weightsv2_comb_reorg_ap16.bin`
> 
> I think the same will happen when I try to load `biasv2_comb_ap16.bin` and perhaps some other files. Is there any way I can get the missing files?

You should follow the Software Verison codes to generate these files that you need.
