### ISSUE TITLE
What are the proper values for Tm, Tn, Tr, Tc

### ISSUE THREAD

**Issue by chesterkyles** [dhm2013724/yolov2_xilinx_fpga#64]
Hello, I would just like to ask if how did you able to finalize the values for Tm, Tn, Tr, Tc.
Did you have experimentation of different values for Tm, Tn, Tr, Tc on what is the optimal case?

I assume you followed the Chen Zhang methods in his paper "Optimizing FPGA-based Accelerator Design for Deep Convolutional Neural Networks" for the tile size selection.

Please enlighten me, Thank you. :)

**Comment by dhm2013724** [comment]
> Hello, I would just like to ask if how did you able to finalize the values for Tm, Tn, Tr, Tc.
> Did you have experimentation of different values for Tm, Tn, Tr, Tc on what is the optimal case?
> 
> I assume you followed the Chen Zhang methods in his paper "Optimizing FPGA-based Accelerator Design for Deep Convolutional Neural Networks" for the tile size selection.
> 
> Please enlighten me, Thank you. :)

For the first version, I just selected one specific combination of Tm, Tn, Tr, Tc. Furthermore, I tried to use roofline model to explore the design space that can get the optimal comb in some case.

Chen Zhang's paper mainly focoused on two points : (1) use loop optimizations(unrolling, tiling, and exchange) to design parallel units (2) explore and evaluate different design through roofline model.

So, the key points are roofline model and design template that can be quantized by some design parameters.
