### ISSUE TITLE
Why my detection results like this on zedboard?? did i miss anythings?

### ISSUE THREAD

**Issue by overing1314** [dhm2013724/yolov2_xilinx_fpga#67]
![image](https://user-images.githubusercontent.com/36887809/75846903-9c233300-5e18-11ea-9d49-4fcff7d0766d.png)

**Comment by overing1314** [comment]
thanks。 i solved it

**Comment by leolu12345** [comment]
How did you solve it,help me please, my wechat:18310165373

**Comment by khoinguyenph** [comment]
> thanks。 i solved it

I am stucking in SDK , I can not come to this step like your result. Could you show how could you do?

**Comment by LyvongKEAM** [comment]
> thanks。 i solved it

Can you help me I face that problem while testing on petaLinux. I used source code of float32 @overing1314 

![Image](https://github.com/user-attachments/assets/565a5d6d-c608-4e28-88b9-2af16e26719d)
