### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by liutongxue123** [dhm2013724/yolov2_xilinx_fpga#8]
您好，请问是否可以分享zedboard移植yolo的代码？

**Comment by dhm2013724** [comment]
今天看看能不能把PYNQ版的先更新一下吧，最近忙着毕业，所以一直鸽。。。

**Comment by liutongxue123** [comment]
跪谢大佬，请问方便加一下您的微信么




| |
15522709725
邮箱：15522709725@163.com
|

签名由 网易邮箱大师 定制

在2019年02月25日 17:54，dhm2013724 写道：

今天看看能不能把PYNQ版的先更新一下吧，最近忙着毕业，所以一直鸽。。。
